#!/usr/bin/env python3
"""Regenerate/check Unicode tables and audit references with CPython 3.12."""
import argparse
from pathlib import Path
import re
import sys
import unicodedata as ud

ROOT = Path(__file__).resolve().parents[1]


def scalars():
    return (cp for cp in range(0x110000) if not 0xD800 <= cp <= 0xDFFF)


def ranges(items):
    result = []
    for cp, value in items:
        if result and cp == result[-1][1] + 1 and value == result[-1][2]:
            result[-1] = (result[-1][0], cp, value)
        else:
            result.append((cp, cp, value))
    return result


def tables():
    keys, offsets, data, combining, composing = [], [0], [], [], []
    cased, ignorable, lower, alnum = [], [], [], []
    for cp in scalars():
        ch = chr(cp)
        if ch.isalnum():
            alnum.append((cp, 1))
        nfkd = ud.normalize("NFKD", ch)
        if nfkd != ch and not 0xAC00 <= cp < 0xAC00 + 11172:
            keys.append(cp)
            data.extend(map(ord, nfkd))
            offsets.append(len(data))
        cc = ud.combining(ch)
        if cc:
            combining.append((cp, cc))
        decomposition = ud.decomposition(ch).split()
        if len(decomposition) == 2 and not decomposition[0].startswith("<"):
            first, second = (int(x, 16) for x in decomposition)
            if ud.normalize("NFC", chr(first) + chr(second)) == ch:
                composing.append(((first << 32) | second, cp))
        a = (ch + "Σ").lower().endswith("ς")
        b = ("A" + ch + "Σ").lower().endswith("ς") and not a
        if a:
            cased.append((cp, 1))
        if b:
            ignorable.append((cp, 1))
        lo = ch.lower()
        if lo != ch:
            # U+0130 is replaced with I before lowercase feature extraction.
            # Its unused table entry retains the first scalar of the mapping.
            lower.append((cp, ord(lo[0])))
    return {
        "pos_unicode_tables.rs": {"ALNUM": ("(u32, u32)", [(lo, hi) for lo, hi, _ in ranges(alnum)])},
        "nfkd_tables.rs": {
            "NFKD_KEYS": ("u32", keys), "NFKD_OFFSETS": ("u32", offsets),
            "NFKD_DATA": ("u32", data), "CCC_RANGES": ("(u32, u32, u8)", ranges(combining)),
            "COMPOSE": ("(u64, u32)", sorted(composing)),
        },
        "unicode_tables.rs": {
            "CASED_STOP": ("(u32, u32)", [(lo, hi) for lo, hi, _ in ranges(cased)]),
            "CASE_IGNORABLE": ("(u32, u32)", [(lo, hi) for lo, hi, _ in ranges(ignorable)]),
            "LOWER": ("(u32, u32)", lower),
        },
    }


def check_or_write(write):
    for filename, arrays in tables().items():
        path = ROOT / "src" / filename
        if write:
            parts = ["//! Generated by tools/unicode.py from CPython 3.12 / Unicode 15.0.0.\n"]
            for name, (kind, values) in arrays.items():
                parts.append(f"#[rustfmt::skip]\npub(crate) static {name}: [{kind}; {len(values)}] = [")
                for value in values:
                    literal = ("(" + ", ".join(hex(v) for v in value) + ")"
                               if isinstance(value, tuple) else hex(value))
                    parts.append(f"    {literal},")
                parts.append("];\n")
            if "LOWER" in arrays:
                values = arrays["LOWER"][1]
                parts.extend([f"pub(crate) const LOWER_MIN: u32 = {hex(values[0][0])};",
                              f"pub(crate) const LOWER_MAX: u32 = {hex(values[-1][0])};"])
            path.write_text("\n".join(parts) + "\n", encoding="utf-8")
        body = path.read_text(encoding="utf-8")
        for name, (_, values) in arrays.items():
            match = re.search(rf"static {name}:.*?=\s*\[(.*?)\];", body, re.S)
            if not match:
                raise SystemExit(f"missing table {name}")
            actual = [int(x, 0) for x in re.findall(r"0[xX][0-9a-fA-F]+|\d+", match[1])]
            expected = [v for row in values for v in (row if isinstance(row, tuple) else (row,))]
            if actual != expected:
                raise SystemExit(f"Unicode table mismatch: {filename}/{name}")
            print(f"verified {name}: {len(values)} entries")
        if "LOWER" in arrays:
            for name, expected in (("LOWER_MIN", arrays["LOWER"][1][0][0]),
                                   ("LOWER_MAX", arrays["LOWER"][1][-1][0])):
                match = re.search(rf"const {name}: u32 = (0[xX][0-9a-fA-F]+|\d+);", body)
                if not match or int(match[1], 0) != expected:
                    raise SystemExit(f"Unicode bound mismatch: {name}")


def cps(text):
    return ",".join(f"{ord(ch):X}" for ch in text)


def references(path, sweeps):
    path.mkdir(parents=True, exist_ok=True)
    with (path / "singles.tsv").open("w", encoding="utf-8") as out:
        for cp in scalars():
            ch = chr(cp)
            nf, lo = ud.normalize("NFKC", ch), ch.lower()
            if nf != ch or lo != ch:
                out.write(f"{cp:X}\t{cps(nf)}\t{cps(lo)}\n")
    print(f"wrote {path / 'singles.tsv'}")
    if not sweeps:
        return
    marks, second = [], set()
    for cp in scalars():
        ch = chr(cp)
        if ud.combining(ch):
            marks.append(cp)
        decomposition = ud.decomposition(ch).split()
        if len(decomposition) == 2 and not decomposition[0].startswith("<"):
            second.add(int(decomposition[1], 16))
    second = sorted(second)
    for name, values in (("marks", marks), ("second", second)):
        (path / f"py312_{name}.txt").write_text("".join(f"{cp:X}\n" for cp in values), encoding="utf-8")
    with (path / "py312_compose.tsv").open("w", encoding="utf-8") as out:
        for cp in scalars():
            for mark in second:
                text = chr(cp) + chr(mark)
                nf = ud.normalize("NFKC", text)
                if nf != text:
                    out.write(f"{cp:X},{mark:X}\t{cps(nf)}\n")
    with (path / "py312_order.tsv").open("w", encoding="utf-8") as out:
        for m1 in marks:
            for m2 in marks:
                text = "a" + chr(m1) + chr(m2)
                nf = ud.normalize("NFKC", text)
                if nf != text:
                    out.write(f"{m1:X},{m2:X}\t{cps(nf)}\n")
    print(f"wrote combining sweeps: {len(second)} composing marks, {len(marks)} combining marks")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="check committed table values (default)")
    mode.add_argument("--write", action="store_true", help="regenerate tables")
    parser.add_argument("--references", type=Path, help="also generate exhaustive scalar audit data")
    parser.add_argument("--sweeps", action="store_true", help="also generate 95M combining-sequence references")
    args = parser.parse_args()
    if (sys.implementation.name, sys.version_info[:2], ud.unidata_version) != ("cpython", (3, 12), "15.0.0"):
        raise SystemExit("use CPython 3.12 / Unicode 15.0.0")
    if args.sweeps and not args.references:
        parser.error("--sweeps requires --references")
    check_or_write(args.write)
    if args.references:
        references(args.references, args.sweeps)


if __name__ == "__main__":
    main()
